In [26]:
import pandas as pd
import numpy as np
import statsmodels.api as sm

In [27]:
pd.set_option('display.max_rows', 15)

In [28]:
df = pd.read_stata("aerdat4.dta")
tab7 = pd.read_stata("tab7.dta")

In [29]:
df.columns

Index(['id', 'bog95smp', 'bog97smp', 'jam93smp', 'sex', 'age', 'age2',
       'hsvisit', 'scyfnsh', 'inschl', 'prsch_c', 'prscha_1', 'prscha_2',
       'vouch0', 'bog95asd', 'bog97asd', 'jam93asd', 'dbogota', 'djamundi',
       'd1995', 'd1997', 'response', 'test_tak', 'sex_name', 'svy', 'd1993',
       'phone', 'darea1', 'darea2', 'darea3', 'darea4', 'darea5', 'darea6',
       'darea7', 'darea8', 'darea9', 'darea10', 'darea11', 'darea12',
       'darea13', 'darea14', 'darea15', 'darea16', 'darea17', 'darea18',
       'darea19', 'dmonth1', 'dmonth2', 'dmonth3', 'dmonth4', 'dmonth5',
       'dmonth6', 'dmonth7', 'dmonth8', 'dmonth9', 'dmonth10', 'dmonth11',
       'dmonth12', 'bog95', 'bog97', 'mom_sch', 'mom_age', 'mom_mw', 'dad_sch',
       'dad_age', 'dad_mw', 'sex2', 'strata1', 'strata2', 'strata3', 'strata4',
       'strata5', 'strata6', 'stratams', 'rept6', 'totscyrs', 'haschild',
       'married', 'working', 'rept', 'nrept', 'finish6', 'finish7', 'finish8',
       'sex_miss', 'usngsch', 'hoursum', 'tab3smpl', 'working3'],
      dtype='object')

In [30]:
tab7.columns

Index(['id', 'fechamm', 'q27grade', 'citynum', 'q38grade', 'vouch0', 'year',
       'intervwr', 'bog95smp', 'bog97smp', 'jam93smp', 'sex', 'svy', 'misscc',
       'dbogota', 'djamundi', 'dbosa', 'dcartag', 'd1995', 'd1993', 'd1996',
       'd1997', 'yrapp', 'age', 'age2', 'ageapp', 'response', 'hsvisit',
       'phone', 'rept6', 'rept7', 'rept8', 'scyfnsh', 'scyenrl', 'inschl',
       'totscyrs', 'darea1', 'darea2', 'darea3', 'darea4', 'darea5', 'darea6',
       'darea7', 'darea8', 'darea9', 'darea10', 'darea11', 'darea12',
       'darea13', 'darea14', 'darea15', 'darea16', 'darea17', 'darea18',
       'darea19', 'dmonth1', 'dmonth2', 'dmonth3', 'dmonth4', 'dmonth5',
       'dmonth6', 'dmonth7', 'dmonth8', 'dmonth9', 'dmonth10', 'dmonth11',
       'dmonth12', 'prscha_1', 'prscha_2', 'prsch_c', 'mvouch0', 'living',
       'haschild', 'viol', 'police', 'married', 'judic', 'working', 'hoursum',
       'wkformal', 'hourmax', 'wagemax', 'rept', 'nrept', 'finish6', 'finish7',
       'finish8', 'strata1', 'strata2', 'strata3', 'strata4', 'strata5',
       'strata6', 'stratams', 'sex2', 'sex_miss', 'usngsch', 'usesch'],
      dtype='object')

In [31]:
loser_bog95_tab7 = tab7[(tab7['vouch0'] == 0) & (tab7['bog95smp'] == 1)]

In [32]:
bog95_tab7 = tab7[tab7['bog95smp'] == 1]

In [33]:
combined_sample = df[df['tab3smpl'] == 1]
combined_sample

,id,bog95smp,bog97smp,jam93smp,sex,age,age2,hsvisit,scyfnsh,inschl,...,rept,nrept,finish6,finish7,finish8,sex_miss,usngsch,hoursum,tab3smpl,working3
3,3.0,1.0,0.0,0.0,0.0,14.0,12.0,0.0,8.0,1.0,...,0.0,0.0,1.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0
4,4.0,1.0,0.0,0.0,1.0,14.0,12.0,0.0,8.0,1.0,...,0.0,0.0,1.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0
5,5.0,1.0,0.0,0.0,0.0,14.0,12.0,0.0,8.0,1.0,...,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0
6,6.0,1.0,0.0,0.0,0.0,12.0,10.0,0.0,7.0,1.0,...,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
10,10.0,1.0,0.0,0.0,1.0,14.0,11.0,0.0,8.0,1.0,...,0.0,0.0,1.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21473,21473.0,0.0,1.0,0.0,0.0,13.0,12.0,0.0,6.0,1.0,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
21476,21476.0,0.0,1.0,0.0,0.0,13.0,13.0,0.0,7.0,1.0,...,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
21479,21479.0,0.0,1.0,0.0,0.0,15.0,14.0,0.0,6.0,1.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
21480,21480.0,0.0,1.0,0.0,0.0,12.0,11.0,0.0,7.0,1.0,...,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
21483,21483.0,0.0,1.0,0.0,1.0,14.0,13.0,0.0,7.0,1.0,...,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0

In [34]:
bog95_sample = combined_sample[combined_sample['bog95smp'] == 1]
bog95_sample

,id,bog95smp,bog97smp,jam93smp,sex,age,age2,hsvisit,scyfnsh,inschl,...,rept,nrept,finish6,finish7,finish8,sex_miss,usngsch,hoursum,tab3smpl,working3
3,3.0,1.0,0.0,0.0,0.0,14.0,12.0,0.0,8.0,1.0,...,0.0,0.0,1.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0
4,4.0,1.0,0.0,0.0,1.0,14.0,12.0,0.0,8.0,1.0,...,0.0,0.0,1.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0
5,5.0,1.0,0.0,0.0,0.0,14.0,12.0,0.0,8.0,1.0,...,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0
6,6.0,1.0,0.0,0.0,0.0,12.0,10.0,0.0,7.0,1.0,...,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
10,10.0,1.0,0.0,0.0,1.0,14.0,11.0,0.0,8.0,1.0,...,0.0,0.0,1.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3997,3997.0,1.0,0.0,0.0,0.0,16.0,NaN,1.0,6.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4006,4006.0,1.0,0.0,0.0,0.0,14.0,12.0,0.0,8.0,1.0,...,0.0,0.0,1.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0
4022,4022.0,1.0,0.0,0.0,0.0,16.0,13.0,0.0,8.0,1.0,...,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0
4023,4023.0,1.0,0.0,0.0,0.0,16.0,13.0,0.0,8.0,1.0,...,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0
4030,4030.0,1.0,0.0,0.0,1.0,14.0,11.0,0.0,8.0,1.0,...,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0

In [35]:
dependent_variables_table3 = ['usngsch','prscha_1','prscha_2','prsch_c','scyfnsh','inschl','finish6','finish7','finish8','rept6','rept','nrept','totscyrs']

In [36]:
loser_bog95 = bog95_sample[bog95_sample['vouch0'] == 0]
loser_bog95

,id,bog95smp,bog97smp,jam93smp,sex,age,age2,hsvisit,scyfnsh,inschl,...,rept,nrept,finish6,finish7,finish8,sex_miss,usngsch,hoursum,tab3smpl,working3
4,4.0,1.0,0.0,0.0,1.0,14.0,12.0,0.0,8.0,1.0,...,0.0,0.0,1.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0
5,5.0,1.0,0.0,0.0,0.0,14.0,12.0,0.0,8.0,1.0,...,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0
6,6.0,1.0,0.0,0.0,0.0,12.0,10.0,0.0,7.0,1.0,...,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
12,12.0,1.0,0.0,0.0,1.0,14.0,12.0,0.0,8.0,1.0,...,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0
16,16.0,1.0,0.0,0.0,0.0,15.0,13.0,1.0,7.0,0.0,...,0.0,0.0,1.0,1.0,0.0,0.0,0.0,8.0,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3902,3902.0,1.0,0.0,0.0,0.0,17.0,12.0,0.0,8.0,1.0,...,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0
3945,3945.0,1.0,0.0,0.0,0.0,18.0,15.0,0.0,9.0,0.0,...,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0
4022,4022.0,1.0,0.0,0.0,0.0,16.0,13.0,0.0,8.0,1.0,...,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0
4023,4023.0,1.0,0.0,0.0,0.0,16.0,13.0,0.0,8.0,1.0,...,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0
4030,4030.0,1.0,0.0,0.0,1.0,14.0,11.0,0.0,8.0,1.0,...,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0

In [37]:
# Table 3 Column 1 (everything but "ever used a scholarship")

def tab3_col1(dep_var):
    
    loser_mean = loser_bog95[dep_var].mean()
    loser_std = loser_bog95[dep_var].std()
    loser_n = loser_bog95[dep_var].notna().sum()
    
    return round(loser_mean, 4), round(loser_std, 4), loser_n

In [38]:
for dep_var in dependent_variables_table3:
    mean, std, n = tab3_col1(dep_var)
    print(f"{dep_var}: mean={mean}, std={std}, n={n}")

usngsch: mean=0.0569, std=0.2319, n=562
prscha_1: mean=0.8772, std=0.3285, n=562
prscha_2: mean=0.6726, std=0.4697, n=562
prsch_c: mean=0.5391, std=0.4989, n=562
scyfnsh: mean=7.4858, std=0.965, n=562
inschl: mean=0.831, std=0.3751, n=562
finish6: mean=0.9431, std=0.2319, n=562
finish7: mean=0.847, std=0.3603, n=562
finish8: mean=0.6317, std=0.4828, n=562
rept6: mean=0.194, std=0.4544, n=562
rept: mean=0.2242, std=0.4174, n=562
nrept: mean=0.2544, std=0.5077, n=562
totscyrs: mean=3.653, std=0.951, n=562

In [39]:
# Table 3 Column 1 ("ever used a scholarship")

def tab3_col1_evrsc(dep_var):
    
    loser_mean = loser_bog95_tab7[dep_var].mean()
    loser_std = loser_bog95_tab7[dep_var].std()
    loser_n = loser_bog95_tab7[dep_var].notna().sum()
    
    return round(loser_mean, 4), round(loser_std, 4), loser_n

In [40]:
mean, std, n = tab3_col1_evrsc('usesch')
print(f"{dep_var}: mean={mean}, std={std}, n={n}")

totscyrs: mean=0.2401, std=0.4275, n=579

In [41]:
# Table 3 Column 2 (everything but "ever used a scholarship")

treatment = 'vouch0'

def tab3_col2(dep_var, treatment):

    for var in dependent_variables_table3:
        vars_needed = [treatment, var]
        data = bog95_sample[vars_needed].dropna()

        X = sm.add_constant(data[treatment])
        y = data[var]

        model = sm.OLS(y, X).fit()

        coef = model.params[treatment]
        std_err = model.bse[treatment]
        n = data.shape[0]

        print(f"{var}: coef={round(coef, 4)}, std_err={round(std_err, 4)}, n={n}")

In [42]:
tab3_col2(dependent_variables_table3, treatment)

usngsch: coef=0.5089, std_err=0.023, n=1147
prscha_1: coef=0.0629, std_err=0.0169, n=1147
prscha_2: coef=0.1736, std_err=0.0247, n=1147
prsch_c: coef=0.16, std_err=0.0283, n=1147
scyfnsh: coef=0.1638, std_err=0.053, n=1147
inschl: coef=0.0186, std_err=0.0216, n=1147
finish6: coef=0.0262, std_err=0.012, n=1147
finish7: coef=0.0402, std_err=0.02, n=1147
finish8: coef=0.1119, std_err=0.0272, n=1147
rept6: coef=-0.0657, std_err=0.0243, n=1147
rept: coef=-0.0601, std_err=0.0233, n=1147
nrept: coef=-0.0733, std_err=0.0278, n=1147
totscyrs: coef=0.0581, std_err=0.0524, n=1147

In [43]:
# Table 3 Column 2 ("ever used a scholarship")

def tab3_col2_evrsc(dep_var, treatment):

    vars_needed = [treatment, dep_var]
    data = bog95_tab7[vars_needed].dropna()

    X = sm.add_constant(data[treatment])
    y = data[dep_var]

    model = sm.OLS(y, X).fit()

    coef = model.params[treatment]
    std_err = model.bse[treatment]
    n = data.shape[0]

    print(f"{dep_var}: coef={round(coef, 4)}, std_err={round(std_err, 4)}, n={n}")

In [44]:
tab3_col2_evrsc('usesch', treatment)

usesch: coef=0.6755, std_err=0.021, n=1171

In [110]:
# Table 3 Column 3 (everything but "ever used a scholarship")
controls = ['age','sex2','hsvisit','dmonth1','dmonth2','dmonth3','dmonth4','dmonth5','dmonth6','dmonth7','dmonth8','dmonth9','sex_miss',
            'dmonth10','dmonth11','dmonth12','phone','svy','strata1','strata2','strata3','strata4','strata5','strata6','stratams','djamundi','dbogota','d1993','d1995','d1997']

def tab3_col3(dep_var, treatment, controls):

    for var in dep_var:
        vars_needed = [treatment, var] + controls
        data = bog95_sample[vars_needed].dropna()

        X = sm.add_constant(data[[treatment] + controls])
        y = data[var]

        model = sm.OLS(y, X).fit()

        coef = model.params[treatment]
        std_err = model.bse[treatment]
        n = data.shape[0]

        print(f"{var}: coef={round(coef, 4)}, std_err={round(std_err, 4)}, n={n}")

In [111]:
tab3_col3(dependent_variables_table3, treatment, controls)

usngsch: coef=0.5042, std_err=0.0229, n=1147
prscha_1: coef=0.0574, std_err=0.017, n=1147
prscha_2: coef=0.1681, std_err=0.0247, n=1147
prsch_c: coef=0.1533, std_err=0.0278, n=1147
scyfnsh: coef=0.1301, std_err=0.0517, n=1147
inschl: coef=0.0069, std_err=0.0203, n=1147
finish6: coef=0.0229, std_err=0.012, n=1147
finish7: coef=0.0307, std_err=0.0198, n=1147
finish8: coef=0.1002, std_err=0.027, n=1147
rept6: coef=-0.0594, std_err=0.0246, n=1147
rept: coef=-0.0548, std_err=0.0235, n=1147
nrept: coef=-0.0667, std_err=0.0279, n=1147
totscyrs: coef=0.0337, std_err=0.0509, n=1147

In [112]:
# Table 3 Column 3 ("ever used a scholarship")

def tab3_col3_evrsc(dep_var, treatment, controls):

    vars_needed = [treatment, dep_var] + controls
    data = bog95_tab7[vars_needed].dropna()

    X = sm.add_constant(data[[treatment] + controls])
    y = data[dep_var]

    model = sm.OLS(y, X).fit()

    coef = model.params[treatment]
    std_err = model.bse[treatment]
    n = data.shape[0]

    print(f"{dep_var}: coef={round(coef, 4)}, std_err={round(std_err, 4)}, n={n}")

tab3_col3_evrsc('usesch', treatment, controls)

usesch: coef=0.6676, std_err=0.0212, n=1171

In [113]:
# Table 3 Column 4 (everything but "ever used a scholarship")
controls_w_barrios = ['age','sex2','hsvisit','dmonth1','dmonth2','dmonth3','dmonth4','dmonth5','dmonth6','dmonth7','dmonth8','dmonth9',
            'dmonth10','dmonth11','dmonth12','phone','svy','strata1','strata2','strata3','strata4','strata5','strata6','stratams',
            'djamundi','dbogota','d1993','d1995','d1997','darea1','darea2','darea3','darea4','darea5','darea6','darea7','darea8','darea9',
            'darea10','darea11','darea12','darea13','darea14','darea15','darea16','darea17','darea18','darea19']

def tab3_col4(dep_var, treatment, controls):

    for var in dep_var:
        vars_needed = [treatment, var] + controls
        data = bog95_sample[vars_needed].dropna()

        X = sm.add_constant(data[[treatment] + controls])
        y = data[var]

        model = sm.OLS(y, X).fit()

        coef = model.params[treatment]
        std_err = model.bse[treatment]
        n = data.shape[0]

        print(f"{var}: coef={round(coef, 4)}, std_err={round(std_err, 4)}, n={n}")

In [114]:
tab3_col4(dependent_variables_table3, treatment, controls_w_barrios)

usngsch: coef=0.5051, std_err=0.023, n=1147
prscha_1: coef=0.0581, std_err=0.017, n=1147
prscha_2: coef=0.1707, std_err=0.0246, n=1147
prsch_c: coef=0.1556, std_err=0.0277, n=1147
scyfnsh: coef=0.1204, std_err=0.0519, n=1147
inschl: coef=0.007, std_err=0.0204, n=1147
finish6: coef=0.0212, std_err=0.0121, n=1147
finish7: coef=0.0285, std_err=0.0199, n=1147
finish8: coef=0.0945, std_err=0.027, n=1147
rept6: coef=-0.0589, std_err=0.0248, n=1147
rept: coef=-0.0509, std_err=0.0237, n=1147
nrept: coef=-0.0636, std_err=0.0282, n=1147
totscyrs: coef=0.0308, std_err=0.051, n=1147

In [115]:
# Table 3 Column 4 ("ever used a scholarship")

def tab3_col4_evrsc(dep_var, treatment, controls):

    vars_needed = [treatment, dep_var] + controls
    data = bog95_tab7[vars_needed].dropna()

    X = sm.add_constant(data[[treatment] + controls])
    y = data[dep_var]

    model = sm.OLS(y, X).fit()

    coef = model.params[treatment]
    std_err = model.bse[treatment]
    n = data.shape[0]

    print(f"{dep_var}: coef={round(coef, 4)}, std_err={round(std_err, 4)}, n={n}")

tab3_col4_evrsc('usesch', treatment, controls_w_barrios)

usesch: coef=0.6673, std_err=0.0213, n=1171

In [141]:
# Table 3 Column 5 (everything but "ever used a scholarship")

def tab3_col5(dep_var, treatment, controls):

    for var in dep_var:
        vars_needed = [treatment, var] + controls
        if var in ['finish7', 'finish8']:
            data = combined_sample[combined_sample['bog97smp'] == 0][vars_needed].dropna()
        else:
            data = combined_sample[vars_needed].dropna()

        X = sm.add_constant(data[[treatment] + controls])
        y = data[var]

        model = sm.OLS(y, X).fit()

        coef = model.params[treatment]
        std_err = model.bse[treatment]
        n = data.shape[0]

        print(f"{var}: coef={round(coef, 4)}, std_err={round(std_err, 4)}, n={n}")

In [142]:
tab3_col5(dependent_variables_table3, treatment, controls)

usngsch: coef=0.5198, std_err=0.0193, n=1577
prscha_1: coef=0.0661, std_err=0.016, n=1577
prscha_2: coef=0.1703, std_err=0.0214, n=1577
prsch_c: coef=0.1523, std_err=0.0233, n=1577
scyfnsh: coef=0.0854, std_err=0.0415, n=1577
inschl: coef=-0.0016, std_err=0.0165, n=1577
finish6: coef=0.0138, std_err=0.0107, n=1577
finish7: coef=0.0271, std_err=0.0177, n=1304
finish8: coef=0.0809, std_err=0.0246, n=1304
rept6: coef=-0.0494, std_err=0.0197, n=1577
rept: coef=-0.0548, std_err=0.0191, n=1577
nrept: coef=-0.058, std_err=0.0224, n=1577
totscyrs: coef=0.0148, std_err=0.044, n=1577

In [129]:
# Table 3 Column 5 ("ever used a scholarship")

def tab3_col5_evrsc(dep_var, treatment, controls):

    vars_needed = [treatment, dep_var] + controls
    data = tab7[(tab7['bog95smp'] == 1) | (tab7['bog97smp'] == 1) | (tab7['jam93smp'])][vars_needed].dropna()

    X = sm.add_constant(data[[treatment] + controls])
    y = data[dep_var]

    model = sm.OLS(y, X).fit()

    coef = model.params[treatment]
    std_err = model.bse[treatment]
    n = data.shape[0]

    print(f"{dep_var}: coef={round(coef, 4)}, std_err={round(std_err, 4)}, n={n}")

tab3_col5_evrsc('usesch', treatment, controls)

usesch: coef=0.6375, std_err=0.0187, n=1610

In [139]:
# Table 3 Column 6 (everything but "ever used a scholarship")

def tab3_col6(dep_var, treatment, controls):

    for var in dep_var:
        vars_needed = [treatment, var] + controls
        if var in ['finish7', 'finish8']:
            data = combined_sample[combined_sample['bog97smp'] == 0][vars_needed].dropna()
        else:
            data = combined_sample[vars_needed].dropna()
        X = sm.add_constant(data[[treatment] + controls])
        y = data[var]

        model = sm.OLS(y, X).fit()

        coef = model.params[treatment]
        std_err = model.bse[treatment]
        n = data.shape[0]

        print(f"{var}: coef={round(coef, 4)}, std_err={round(std_err, 4)}, n={n}")

In [140]:
tab3_col6(dependent_variables_table3, treatment, controls_w_barrios)

usngsch: coef=0.5214, std_err=0.0193, n=1577
prscha_1: coef=0.0673, std_err=0.016, n=1577
prscha_2: coef=0.1727, std_err=0.0213, n=1577
prsch_c: coef=0.1544, std_err=0.0233, n=1577
scyfnsh: coef=0.0777, std_err=0.0416, n=1577
inschl: coef=-0.0021, std_err=0.0166, n=1577
finish6: coef=0.0124, std_err=0.0108, n=1577
finish7: coef=0.0251, std_err=0.0178, n=1304
finish8: coef=0.0765, std_err=0.0246, n=1304
rept6: coef=-0.0494, std_err=0.0198, n=1577
rept: coef=-0.0531, std_err=0.0192, n=1577
nrept: coef=-0.0568, std_err=0.0225, n=1577
totscyrs: coef=0.0118, std_err=0.0441, n=1577

In [144]:
# Table 3 Column 6 ("ever used a scholarship")

def tab3_col6_evrsc(dep_var, treatment, controls):

    vars_needed = [treatment, dep_var] + controls
    data = tab7[(tab7['bog95smp'] == 1) | (tab7['bog97smp'] == 1) | (tab7['jam93smp'])][vars_needed].dropna()

    X = sm.add_constant(data[[treatment] + controls])
    y = data[dep_var]

    model = sm.OLS(y, X).fit()

    coef = model.params[treatment]
    std_err = model.bse[treatment]
    n = data.shape[0]

    print(f"{dep_var}: coef={round(coef, 4)}, std_err={round(std_err, 4)}, n={n}")

tab3_col6_evrsc('usesch', treatment, controls_w_barrios)

usesch: coef=0.6373, std_err=0.0187, n=1610